* Go from python2 to python3

* Go from QT4 to QT5

* Something wrong loading/saving the "database"
  Look for debug output in terminal!

* Change from "iwconfig" to "iw" or "ip" to get the information,
  Line #136 in "gerix_config.py"

  "if exec_command('iwconfig 2>&1 | grep 802.11 | grep' + interface):"


